version: '3'
networks:
  geth:
    external: true

x-config: &default-config
  logging:
    driver: "json-file"
    options:
      max-size: "200m"
  mem_swappiness: 0
  mem_limit: 128000m

services:
  bsc:
    image: bsc
    container_name: bsc
    restart: unless-stopped
    stop_grace_period: 3m
    networks:
      - geth
    environment:
      - NETWORK=mainnet
    env_file:
      - .env
    <<: *default-config
    entrypoint: geth
    command: >
      --datadir /bsc/node
      --config /bsc/config/config.toml
      --http
      --http.addr 0.0.0.0
      --port 30311
      --http.port 8545
      --http.vhosts=*
      --http.corsdomain=*
      --ws
      --ws.addr=0.0.0.0
      --ws.origins=*
      --http.api=eth,web3,txpool
      --maxpeers=20
      --syncmode=full
      --pruneancient
      --snapshot=false
    ports:
      - 30311:30311
      - ${PORT__RPC__HTTP:-127.0.0.1:8745}:8545
      - ${PORT__RPC__WS:-127.0.0.1:8746}:8546
    volumes:
      - /data/bsc/node:/bsc/node
      - /data/bsc/config:/bsc/config
