---
version: "3.9"
services:
  fullnode:
    image: mysten/sui-node:stable
    container_name: sui
    ports:
    - "8084:8084/udp"
    - "127.0.0.1:9300:9000"
    - "127.0.0.1:9384:9184"
    volumes:
    - ./fullnode-template.yaml:/sui/fullnode.yaml:ro
    - ./genesis.blob:/sui/genesis.blob:ro
    - /data/sui:/sui/suidb
    command: ["/usr/local/bin/sui-node", "--config-path", "fullnode.yaml"]
volumes:
  suidb:
