chain = "mainnet"
identity = "changmesh762hnci97hdgjdychangme"
verbosity = 3
log-level = ""
vmdebug = false
datadir = "/root/.bor"
ancient = ""
# "db.engine" = "leveldb"
# "state.scheme" = "hash"
"db.engine" = "pebble"
"state.scheme" = "path"
keystore = ""
"rpc.batchlimit" = 100
"rpc.returndatalimit" = 100000
syncmode = "full"
gcmode = "full"
snapshot = false
"bor.logs" = false
ethstats = ""
devfakeauthor = false

["eth.requiredblocks"]

[log]
  vmodule = ""
  json = false
  backtrace = ""
  debug = false

[p2p]
  maxpeers = 50
  maxpendpeers = 50
  bind = "0.0.0.0"
  port = 30304
  nodiscover = false
  nat = "any"
  netrestrict = ""
  nodekey = ""
  nodekeyhex = ""
  txarrivalwait = "500ms"
  [p2p.discovery]
    v5disc = false
    bootnodes = ["enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303", "enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303"]
    bootnodesv4 = []
    bootnodesv5 = []
    static-nodes = []
    trusted-nodes = []
    dns = []

[heimdall]
  url = "http://heimdallr:1317"
  "bor.without" = false
  grpc-address = ""
  "bor.runheimdall" = false
  "bor.runheimdallargs" = ""
  "bor.useheimdallapp" = false

[txpool]
  locals = []
  nolocals = false
  journal = "transactions.rlp"
  rejournal = "1h0m0s"
  pricelimit = 1
  pricebump = 10
  accountslots = 16
  globalslots = 32768
  accountqueue = 16
  globalqueue = 32768
  lifetime = "3h0m0s"

[miner]
  mine = false
  etherbase = ""
  extradata = ""
  gaslimit = 30000000
  gasprice = "1000000000"
  recommit = "2m5s"
  commitinterrupt = true

[jsonrpc]
  ipcdisable = false
  ipcpath = ""
  gascap = 50000000
  evmtimeout = "5s"
  txfeecap = 5.0
  allow-unprotected-txs = false
  enabledeprecatedpersonal = false
  [jsonrpc.http]
    enabled = true
    port = 8545
    prefix = ""
    host = "0.0.0.0"
    api = ["eth", "net", "web3", "txpool", "bor", "admin"]
    vhosts = ["*"]
    corsdomain = ["*"]
    ep-size = 40
    ep-requesttimeout = "0s"
  [jsonrpc.ws]
    enabled = true
    port = 8546
    prefix = ""
    host = "0.0.0.0"
    api = ["eth", "net", "web3", "txpool", "bor"]
    origins = ["*"]
    ep-size = 40
    ep-requesttimeout = "0s"
  [jsonrpc.graphql]
    enabled = false
    port = 0
    prefix = ""
    host = ""
    vhosts = ["localhost"]
    corsdomain = ["localhost"]
    ep-size = 0
    ep-requesttimeout = ""
  [jsonrpc.auth]
    jwtsecret = ""
    addr = "localhost"
    port = 8551
    vhosts = ["localhost"]
  [jsonrpc.timeouts]
    read = "10s"
    write = "30s"
    idle = "2m0s"

[gpo]
  blocks = 20
  percentile = 60
  maxheaderhistory = 1024
  maxblockhistory = 1024
  maxprice = "500000000000"
  ignoreprice = "2"

[telemetry]
  metrics = false
  expensive = false
  prometheus-addr = "127.0.0.1:7071"
  opencollector-endpoint = "127.0.0.1:4317"
  [telemetry.influx]
    influxdb = false
    endpoint = ""
    database = ""
    username = ""
    password = ""
    influxdbv2 = false
    token = ""
    bucket = ""
    organization = ""
    [telemetry.influx.tags]

[cache]
  cache = 300000
  gc = 25
  snapshot = 10
  database = 50
  trie = 15
  journal = "triecache"
  rejournal = "1h0m0s"
  noprefetch = false
  preimages = false
  txlookuplimit = 2350000
  triesinmemory = 128
  timeout = "1h0m0s"
  fdlimit = 0

[leveldb]
  compactiontablesize = 2
  compactiontablesizemultiplier = 1.0
  compactiontotalsize = 10
  compactiontotalsizemultiplier = 10.0

[accounts]
  unlock = []
  password = ""
  allow-insecure-unlock = false
  lightkdf = false
  disable-bor-wallet = true

[grpc]
  addr = ":3131"

[developer]
  dev = false
  period = 0
  gaslimit = 11500000

[parallelevm]
  enable = true
  procs = 8

[pprof]
  pprof = false
  port = 6060
  addr = "127.0.0.1"
  memprofilerate = 524288
  blockprofilerate = 0