version: '3'
networks:
  geth:
    external: true

x-config: &default-config
  logging:
    driver: "json-file"
    options:
      max-size: "200m"
  env_file:
    - .env
  mem_swappiness: 0
  mem_limit: 32000m

services:
  #polygon
  heimdall:
    container_name: heimdall
    image: 0xpolygon/heimdall:1.0.2
    <<: *default-config
    restart: unless-stopped
    stop_grace_period: 3m
    networks:
      - geth
    entrypoint: /usr/bin/heimdalld
    command: >
      start
      --home=/heimdall-home
      --chain=mainnet
    ports:
      - 127.0.0.1:26657:26657
      - 26656:26656
    volumes:
      - /data/polygon/heimdall:/heimdall-home

  heimdallr:
    container_name: heimdallr
    image: 0xpolygon/heimdall:1.0.2
    <<: *default-config
    restart: unless-stopped
    stop_grace_period: 3m
    networks:
      - geth
    entrypoint: /usr/bin/heimdalld
    command: >
      rest-server
      --home=/heimdall-home
      --node "tcp://heimdall:26657"
    ports:
      - 127.0.0.1:1317:1317
    volumes:
      - /data/polygon/heimdall:/heimdall-home

  bor:
    container_name: bor
    image: 0xpolygon/bor:1.0.6
    <<: *default-config
    mem_limit: 160000m
    restart: unless-stopped
    stop_grace_period: 10m
    networks:
      - geth
    command: >
      server
      --config /root/config.toml
    ports:
      - 30304:30304
      - ${PORT__RPC__HTTP:-127.0.0.1:8945}:8545
      - ${PORT__RPC__WS:-127.0.0.1:8946}:8546
    volumes:
      - ./config.toml:/root/config.toml
      - /data/polygon/bor-home:/root/.bor
      # map ancient folder separately, you can place ancient folder in separate drive
      # - /data/polygon/bor-home/bor/chaindata/ancient:/root/.bor/chaindata/ancient
  # check syncing:
  # curl 'localhost:8945/' --header 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
