version: '3'
networks:
  geth:
    external: true

x-config: &default-config
  logging:
    driver: "json-file"
    options:
      max-size: "200m"
  mem_swappiness: 0
  mem_limit: 32000m

services:
  #polygon
  heimdall:
    container_name: heimdall
    image: 0xpolygon/heimdall:0.3.0
    <<: *default-config
    restart: unless-stopped
    networks:
      - geth
    entrypoint: /usr/bin/heimdalld
    command: >
      start
      --home=/heimdall-home
    ports:
      - 127.0.0.1:26657:26657
      - 26656:26656
    volumes:
      - /data/polygon/heimdall:/heimdall-home

  heimdallr:
    container_name: heimdallr
    image: 0xpolygon/heimdall:0.3.0
    <<: *default-config
    restart: unless-stopped
    networks:
      - geth
    entrypoint: /usr/bin/heimdalld
    command: >
      rest-server
      --home=/heimdall-home
      --node "tcp://heimdall:26657"
    ports:
      - 127.0.0.1:1317:1317
    volumes:
      - /data/polygon/heimdall:/heimdall-home

  bor:
    container_name: bor
    image: 0xpolygon/bor:0.3.3-amd64
    <<: *default-config
    mem_limit: 256000m
    restart: unless-stopped
    networks:
      - geth
    command: >
      --datadir /bor-home
      --port 30304
      --bor.heimdall 'http://heimdallr:1317' 
      --http --http.addr '0.0.0.0' 
      --http.vhosts '*' 
      --http.corsdomain '*' 
      --http.port 8545 
      --cache 102400
      --ws
      --ws.port 8546
      --ws.addr '0.0.0.0'
      --ws.origins '*'
      --ipcpath /bor-home/bor.ipc 
      --http.api 'eth,net,web3,txpool,bor' 
      --syncmode 'full'
      --miner.gasprice '30000000000' 
      --miner.gaslimit '20000000' 
      --txpool.nolocals 
      --txpool.accountslots 16 
      --txpool.globalslots 32768 
      --txpool.accountqueue 16 
      --txpool.globalqueue 32768 
      --txpool.pricelimit '30000000000' 
      --txpool.lifetime '1h30m0s' 
      --maxpeers 20
      --bootnodes "enode://0cb82b395094ee4a2915e9714894627de9ed8498fb881cec6db7c65e8b9a5bd7f2f25cc84e71e89d0947e51c76e85d0847de848c7782b13c0255247a6758178c@44.232.55.71:30303,enode://88116f4295f5a31538ae409e4d44ad40d22e44ee9342869e7d68bdec55b0f83c1530355ce8b41fbec0928a7d75a5745d528450d30aec92066ab6ba1ee351d710@159.203.9.164:30303"
    ports:
      - 30304:30304
      - 127.0.0.1:8945:8545
      - 127.0.0.1:8946:8546
    volumes:
      - /data/polygon/bor-home:/bor-home/
      # map ancient folder separately, you can place ancient folder in separate drive
      - /data/polygon/bor-home/bor/chaindata/ancient:/bor-home/bor/chaindata/ancient
  # check syncing:
  # curl 'localhost:8945/' --header 'Content-Type: application/json' -d '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":1}'
