version: '3.8'
networks:
  geth:
    external: true

x-config: &default-config
  logging:
    driver: "json-file"
    options:
      max-size: "200m"
  mem_swappiness: 0
  mem_limit: 64000m

services:
  # Primary Ethereum instance
  ethereum:
    image: ${DOCKER__IMAGE:-ethereum/client-go:v1.14.11}
    container_name: ethereum
    restart: unless-stopped
    stop_grace_period: 3m
    env_file:
      - .env
    <<: *default-config
    networks:
      - geth
    command: >
      --http
      --http.addr 0.0.0.0
      --port 30303
      --http.port 8545
      --http.vhosts=*
      --cache 96000
      --authrpc.jwtsecret=/jwtsecret
      --authrpc.port 8551
      --authrpc.addr=0.0.0.0
      --authrpc.vhosts=ethereum
      --ws
      --ws.addr=0.0.0.0
      --ws.origins=*
      --http.api=eth,web3,debug,txpool,net
      --maxpeers=20
      --txlookuplimit 0
      --syncmode snap
    ports:
      - ${PORT__RPC__HTTP:-127.0.0.1:8545}:8545
      - ${PORT__RPC__WS:-127.0.0.1:8546}:8546
      - 127.0.0.1:8551:8551
      - 30303:30303
    volumes:
      - /data/geth:/root/.ethereum
      # ETH2 beacon chain node secret file for AuthRPC.
      # Share with your beacon client.
      # Generate this file: openssl rand -hex 32 > jwtsecret
      # and share to beacon chain node.
      - /data/geth/jwtsecret:/jwtsecret
#  beacon-node:
#    networks:
#      - geth
#    image: gcr.io/prysmaticlabs/prysm/beacon-chain:stable
#    container_name: beacon-node
#    <<: *default-config
#    ports:
#      - "4000:4000"
#      - "13000:13000"
#      - "12000:12000/udp"
#    volumes:
#      - /data/prysm:/data
#      - /data/ethereum:/ethereum
#    command:
#      [
#        "--datadir=/data",
#        "--jwt-secret=/ethereum/jwtsecret",
#        "--rpc-host=0.0.0.0",
#        "--http-host=0.0.0.0",
#        "--monitoring-host=0.0.0.0",
#        "--slots-per-archive-point=32",
#        "--mainnet",
#        "--accept-terms-of-use",
#        "--execution-endpoint=http://ethereum:8551",
#        "--checkpoint-sync-url=https://sync-mainnet.beaconcha.in",
#        "--genesis-beacon-api-url=https://sync-mainnet.beaconcha.in",
#        "--datadir=/data/ethereum/prysm",
#        "--enable-experimental-backfill=true"
#      ]
  teku:
    networks:
      - geth
    image: consensys/teku:latest
    container_name: teku
    <<: *default-config
    restart: unless-stopped
    ports:
      - "9000:9000/tcp"
      - "9000:9000/udp"
      - "5055:5055"
    environment:
      - TEKU_REST_API_ENABLED=true
      - TEKU_P2P_PORT=9000
    volumes:
      - /data/teku/:/var/lib/teku
      - /data/geth/jwtsecret:/jwtsecret
    command:
      - --network=mainnet
      - --eth1-endpoint=http://ethereum:8545
      - --ee-endpoint=http://ethereum:8551
      - --ee-jwt-secret-file=/jwtsecret
      - --data-path=/var/lib/teku
      - --rest-api-port=5055
      - --rest-api-enabled=true
      - --rest-api-cors-origins="*"
      #- --rest-api-interface="0.0.0.0"
      - --rest-api-host-allowlist="*"
      - --checkpoint-sync-url=https://sync-mainnet.beaconcha.in
      - --log-destination=CONSOLE
      - --data-storage-mode=archive
